# Generated by Django 5.1.1 on 2024-11-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matomou', '0002_videoentry_video_title_translation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoentry',
            name='video_title_translation',
            field=models.CharField(blank=True, max_length=20000),
        ),
    ]
