# Generated by Django 5.1.1 on 2024-11-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matomou', '0003_alter_videoentry_video_title_translation'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoentry',
            name='bilibili_thumbnail_link',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='videoentry',
            name='niconico_thumbnail_link',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
