# Generated by Django 5.1.1 on 2024-11-18 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matomou', '0008_videoentry_contributed_by_videoentry_uploaded_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='creator',
            name='homepage_url',
            field=models.URLField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='creator',
            name='twitter_url',
            field=models.URLField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='creator',
            name='weibo_url',
            field=models.URLField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='videoentry',
            name='bilibili_thumbnail_link',
            field=models.URLField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='videoentry',
            name='main_url',
            field=models.URLField(max_length=250),
        ),
        migrations.AlterField(
            model_name='videoentry',
            name='niconico_thumbnail_link',
            field=models.URLField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='videoentry',
            name='youtube_thumbnail_link',
            field=models.URLField(blank=True, max_length=250),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_url', models.URLField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
